package endictionary;

import Models.*;
import ObjectInfos.Word;
import java.util.ArrayList;

/**
 *
 * @author Nguyen son Hao CE140386
 */
public class NewWord extends javax.swing.JFrame {

    // Creates model connection
    TypeModel tm;
    MeaningModel mm;
    WordModel wm;
    EnDictionary parent;

    /**
     * Creates new form NewWord
     */
    public NewWord(EnDictionary parent, TypeModel tm, MeaningModel mm, WordModel wm) {
        initComponents();

        this.setLocationRelativeTo(null);

        this.parent = parent;// parameter
        this.tm = tm;// parameter
        this.mm = mm;// parameter
        this.wm = wm;// parameter

        FrmresetNeword();
    }

    /**
     * Reset new word
     */
    public void FrmresetNeword() {
        txtWord.setText("");
        txtMeanging.setText("");
        cmbType.removeAllItems();
        ArrayList<String> lisOfType = tm.getTypeList();
        for (String t : lisOfType) {
            cmbType.addItem(t);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNewWord = new javax.swing.JLabel();
        lblWord = new javax.swing.JLabel();
        lblType = new javax.swing.JLabel();
        lblMeaning = new javax.swing.JLabel();
        cmbType = new javax.swing.JComboBox<>();
        txtWord = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMeanging = new javax.swing.JTextArea();
        btnAdd = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setTitle("EnDictionary V1.0 Add new word");
        setName("frmNewWord"); // NOI18N

        lblNewWord.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblNewWord.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNewWord.setText("ADD NEW WORD");
        lblNewWord.setToolTipText("");

        lblWord.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblWord.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblWord.setText("Word");

        lblType.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblType.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblType.setText("Type");

        lblMeaning.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblMeaning.setText("Meaning");

        txtMeanging.setColumns(20);
        txtMeanging.setRows(5);
        jScrollPane1.setViewportView(txtMeanging);

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/plus.png"))); // NOI18N
        btnAdd.setText("Add new word");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancel.png"))); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNewWord, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblType, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblWord, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblMeaning)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAdd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtWord)
                            .addComponent(cmbType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblNewWord)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblWord)
                    .addComponent(txtWord, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblType)
                    .addComponent(cmbType, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMeaning))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnCancel))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Button add new word
     *
     * @param evt
     */
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String wText = txtWord.getText();

        wm.insert(wText);

        //get wId
        Word word = wm.searchByFullWord(wText);
        int wId = word.getwId();

        String tText = String.valueOf(cmbType.getSelectedItem());
        ObjectInfos.Type type = tm.searchByName(tText);
        int tId = type.gettId();

        //get mean
        String mText = txtMeanging.getText();
        //Inser meaning into database
        mm.insert(wId, tId, mText);

        this.setVisible(false);
        parent.loadDictionary();
        parent.showMeaning(wText);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JComboBox<String> cmbType;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMeaning;
    private javax.swing.JLabel lblNewWord;
    private javax.swing.JLabel lblType;
    private javax.swing.JLabel lblWord;
    private javax.swing.JTextArea txtMeanging;
    private javax.swing.JTextField txtWord;
    // End of variables declaration//GEN-END:variables
}
