package endictionary;

import ObjectInfos.*;
import Models.WordModel;
import java.util.ArrayList;

/**
 *
 * @author Nguyen Son Hao CE140386
 */
public class TestCreator extends javax.swing.JFrame {

    EnDictionary parent;//creates parent
    WordModel wm;//creates wm
    ArrayList<Word> theTest;//creates Arraylist theTest
    ArrayList<String> userInput;//creates Arraylist userInput
    Testing frmTesting = null; // Creates frmTesting 

    /**
     * Creates new form TestCreator
     */
    public TestCreator(EnDictionary parent, WordModel wm, ArrayList<Word> theTest, ArrayList<String> userInput) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setIconImage(getToolkit().getDefaultToolkit().getImage(getClass().getResource("../img/english.png")));
        this.wm = wm;// parameter
        this.theTest = theTest;//parameter
        this.userInput = userInput;//parameter
    }

    /**
     * Refresh
     */
    public void refresh() {
        cmbNumberOfWord.removeAllItems();
        for (int i = 5; i <= wm.getSize(); i++) {// combo box chose question 1 - 10
            cmbNumberOfWord.addItem(i + "");
        }
        chkRandomize.setSelected(true);// if chose yes random question
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTestSetup = new javax.swing.JLabel();
        lblNumberword = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cmbNumberOfWord = new javax.swing.JComboBox<>();
        chkRandomize = new javax.swing.JCheckBox();
        btnOk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EnDictionary V1.0[Test Setup]");

        lblTestSetup.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblTestSetup.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTestSetup.setText("TEST SETUP");
        lblTestSetup.setToolTipText("");

        lblNumberword.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblNumberword.setText("Number of words");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Randomize");

        cmbNumberOfWord.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        chkRandomize.setText("Yes");

        btnOk.setText("OK");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTestSetup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNumberword)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbNumberOfWord, 0, 91, Short.MAX_VALUE)
                            .addComponent(chkRandomize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 19, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTestSetup, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumberword)
                    .addComponent(cmbNumberOfWord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(chkRandomize))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(btnOk)
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Button
     *
     * @param evt
     */
    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed

        int n = Integer.parseInt(String.valueOf(cmbNumberOfWord.getSelectedItem()));// get vale combo box
        boolean isShuffle = chkRandomize.isSelected();// chose random
        theTest = wm.generateTest(n, isShuffle);// Return word
        this.setVisible(false);

        if (frmTesting == null) {
            frmTesting = new Testing(parent, wm, theTest, userInput);
        }
        frmTesting.refresh();// load again
        frmTesting.setSize(1022, 500);
        frmTesting.setVisible(true);

    }//GEN-LAST:event_btnOkActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOk;
    private javax.swing.JCheckBox chkRandomize;
    private javax.swing.JComboBox<String> cmbNumberOfWord;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblNumberword;
    private javax.swing.JLabel lblTestSetup;
    // End of variables declaration//GEN-END:variables
}
