package endictionary;

import Models.*;
import ObjectInfos.Meaning;
import ObjectInfos.Word;
import java.util.ArrayList;

/**
 *
 * @author Nguyen Son Hao CE140386
 */
public class UpdateWord extends javax.swing.JFrame {

    TypeModel tm;
    MeaningModel mm;
    WordModel wm;
    EnDictionary parent;
    int wId, tId;

    /**
     * Creates new form NewWord
     */
    public UpdateWord(EnDictionary parent, TypeModel tm, MeaningModel mm, WordModel wm, int wId) {
        initComponents();
        //Set icon for progarm
        this.setIconImage(getToolkit().getDefaultToolkit().getImage(getClass().getResource("../img/english.png")));
        //Set center
        this.setLocationRelativeTo(null);

        this.parent = parent;
        this.tm = tm;
        this.mm = mm;
        this.wm = wm;
        this.wId = wId;

        loadOldWord();
    }

    /**
     * Load word
     */
    public void loadOldWord() {
        Word word = wm.searchById(wId);
        txtWord.setText(word.getwText());

        ArrayList<Meaning> listofMeaning = mm.getMeanings(wId);
        Meaning meaning = listofMeaning.get(0);
        txtMeanging.setText(meaning.getmText());

        cmbType.removeAllItems();
        ArrayList<String> lisOfType = tm.getTypeList();
        for (String t : lisOfType) {
            cmbType.addItem(t);
        }
        tId = meaning.gettId();
        ObjectInfos.Type type = tm.searchById(tId);
        String tText = type.gettText();

        cmbType.setSelectedItem(tText);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNewWord = new javax.swing.JLabel();
        lblWord = new javax.swing.JLabel();
        lblType = new javax.swing.JLabel();
        lblMeaning = new javax.swing.JLabel();
        cmbType = new javax.swing.JComboBox<>();
        txtWord = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMeanging = new javax.swing.JTextArea();
        btnUpdate = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setTitle("EnDictionary V1.0 Add new word");
        setName("frmNewWord"); // NOI18N

        lblNewWord.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblNewWord.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNewWord.setText("ADD NEW WORD");
        lblNewWord.setToolTipText("");

        lblWord.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblWord.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblWord.setText("Word");

        lblType.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblType.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblType.setText("Type");

        lblMeaning.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblMeaning.setText("Meaning");

        txtMeanging.setColumns(20);
        txtMeanging.setRows(5);
        jScrollPane1.setViewportView(txtMeanging);

        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/update.png"))); // NOI18N
        btnUpdate.setText("Update word");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancel.png"))); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNewWord, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblType, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblWord, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblMeaning)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnUpdate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtWord)
                            .addComponent(cmbType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblNewWord)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblWord)
                    .addComponent(txtWord, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblType)
                    .addComponent(cmbType, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMeaning))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate)
                    .addComponent(btnCancel))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Button update word
     *
     * @param evt
     */
    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        //wid
        String wText = txtWord.getText();

//        Word word = wm.searchByFullWord(wText);
        //get tId
        wm.update(wId, wText);

        //get wId;
        String tText = String.valueOf(cmbType.getSelectedItem());
        ObjectInfos.Type type = tm.searchByName(tText);
        int new_tId = type.gettId();

        //get mean
        String new_mean = txtMeanging.getText();
        //updater meaning into database
        mm.update(wId, tId, new_tId, new_mean);

        this.setVisible(false);
        parent.loadDictionary();
        parent.showMeaning(wText);
    }//GEN-LAST:event_btnUpdateActionPerformed
    /**
     * Button Cancel
     *
     * @param evt
     */
    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbType;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMeaning;
    private javax.swing.JLabel lblNewWord;
    private javax.swing.JLabel lblType;
    private javax.swing.JLabel lblWord;
    private javax.swing.JTextArea txtMeanging;
    private javax.swing.JTextField txtWord;
    // End of variables declaration//GEN-END:variables
}
